# Generated by Django 4.1 on 2023-01-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptKeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128, unique=True, verbose_name='Address')),
                ('name', models.CharField(max_length=75, verbose_name='Name')),
                ('eth_name', models.CharField(max_length=128, verbose_name='Eth Name')),
                ('expertise', models.CharField(max_length=120, verbose_name='Expertise')),
                ('why', models.CharField(max_length=4000, verbose_name='Why')),
                ('image', models.CharField(max_length=255, verbose_name='Image')),
                ('discord', models.CharField(max_length=30, verbose_name='Discord')),
                ('twitter', models.CharField(max_length=30, verbose_name='Twitter')),
            ],
            options={
                'verbose_name': 'Crypt. Keeper',
                'verbose_name_plural': 'Crypt. Keepers',
            },
        ),
    ]
