FROM postgres:13.5-alpine

RUN apk update && apk add bash

## RUN psql -U postgres -c "CREATE USER cryptex WITH PASSWORD '123456';"
## RUN psql -U postgres -c "CREATE DATABASE cryptex WITH OWNER cryptex;"